### ISSUE TITLE
Feature Request - Delay to Disable Pawblock

### ISSUE THREAD

**Issue by whatsnewsisyphus** [dguo/pawblock#4]
Hello again. Would it be possible to have an option that would bring up a delay page if you tried to disable pawblock?

**Comment by dguo** [comment]
Hey. What about just making the soft block time apply to the "off" button as well? Would that work for you?

**Comment by whatsnewsisyphus** [comment]
I think that would help people, will it bring up the regular soft delay page asking 'are you sure...?' (I'm recommending this to students who like to use it to kill social media during homework time)

**Comment by dguo** [comment]
I'd rather not go that far, just because the off button is also available from the toolbar, and I'd prefer to keep the popup small. Do you think just having it disabled for a bit is enough?

Thanks for sharing it! I hope they are finding it useful.

**Comment by whatsnewsisyphus** [comment]
Do you mean there would be a timeout in the the little popup or would it happen invisibly? It would be ideal if it did something similar where it asks are you sure with a sad kitty face or something :)

**Comment by dguo** [comment]
I meant there would be a countdown to 0 in the "off" button, and the button would be disabled until the countdown hits 0.

But yeah, it'd be nice to have the picture too. I'll think about it some more.

**Comment by whatsnewsisyphus** [comment]
I can make a silly icon like this if you want :) I just threw it together on illustrator
https://www.dropbox.com/s/3gnj04pe761opnu/Screenshot%202018-01-22%2017.38.42.png
It could appear in a second line with a button that says 'nevermind', turn to smiley if you click it, similar to your original delay page

**Comment by whatsnewsisyphus** [comment]
![silly kittens](https://i.imgur.com/zvd5MSJ.png)
made an embeddable image for ease

**Comment by dguo** [comment]
Haha I like them! Thanks! I'll work on this change / get them added in the next week or so.

**Comment by whatsnewsisyphus** [comment]
Let me know what format you'd like them, I can send them as svg assets or even generate a font

**Comment by dguo** [comment]
svgs would be great.

**Comment by whatsnewsisyphus** [comment]
I made the left one into a pug, improved legibility at scale and made some strokes consistent.
https://gist.github.com/whatsnewsisyphus/bc977ebc3f3334a830ede35ec9cd3665

**Comment by dguo** [comment]
Hi, sorry for the long delay. This feature is available now (once your extension updates). There's now a 5 second delay when you try to turn off PawBlock from the popup. And it uses your images. :)

I only applied it to the popup, and the time length isn't configurable. I'm open to making further changes, but I want to get more feedback first.

**Comment by whatsnewsisyphus** [comment]
Looks great! I'll let students know :)

**Comment by whatsnewsisyphus** [comment]
If people find it too large you can probably make it compact like so, I think it looks better small and is more inline with being a popup.
![screenshot 2018-04-17 00 57 10](https://user-images.githubusercontent.com/454772/38849509-5802af72-41da-11e8-9a4e-b36f27ca3a8d.png)
![screenshot 2018-04-17 00 54 02](https://user-images.githubusercontent.com/454772/38849510-5a6151d8-41da-11e8-9b01-452d424feb41.png)

**Comment by dguo** [comment]
I'll keep that in mind.

Thanks for suggesting this and for contributing the images!
