### ISSUE TITLE
Feature Request: Auto-reenable / Temporary Disable

### ISSUE THREAD

**Issue by whatsnewsisyphus** [dguo/pawblock#7]
Hello Again,
If this is not too difficult to add, I think it would be really helpful -if it is not essential- to make the default behaviour (or have an option) to re-enable after a set period of time. 
Say you have an option of X minutes, pawblock re-enables after X minutes if you turned it off from the toolbar. 
Otherwise one can turn it off and forget about it (thinking within the means of using pawblock to help people having difficulty staying focused.

**Comment by dguo** [comment]
That's an interesting idea! I do have moments where I need to temporarily go to a blocked site for work purposes, and this feature would be helpful for that situation. I'll look into how it would work from a technical perspective.

**Comment by whatsnewsisyphus** [comment]
Is the html of the popup technically always active? Anyhow you could add a background .js to your extension that can handle some variables sent/received by the popup.js, and set by options.js, sort of like:

```
blocktimer (
  turn block off
  if(options.timer){
    set timeout({
      turn block on
    },
    options.timer) 
  }
}
```

popup.js
call blocktimer when toggled off

**Comment by dguo** [comment]
Yep, I already have a background script (to handle the actual block). That sounds right.

**Comment by dguo** [comment]
This feature is available now (once your extension updates). It's optional, and you can configure the number of minutes before it re-enables.
